version: "3.9"
services:
  db:
    image: mysql
    volumes:
      - "dbdata:/var/lib/mysql"
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=financeiro
      - MYSQL_USER=_financeiro
      - MYSQL_PASSWORD=financeiro@123
    ports:
      - "3306:3306"
    networks:
      - financeiro-network
  web:
    build: .
    container_name: financeiro-api
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=user_financeiro
      - DATABASE_NAME=financeiro
      - DATABASE_PORT=3306
    networks:
      - financeiro-network
    depends_on:
      - db
networks:
  financeiro-network:
    driver: bridge
volumes:
  dbdata: